package consts

const (
	BILLING_PLAN_NAME_MAX_LENGTH = 15
	BILLING_PLAN_NAME_MIN_LENGTH = 3

	BILLING_FREE_TIER  = "FREE"
	BILLING_BASIC_TIER = "BASIC"
	BILLING_PRO_TIER   = "PRO"
	BILLING_ULTRA_TIER = "ULTRA"
)
