package consts

const (
	BILLING_PLAN_NAME_MAX_LENGTH = 15
	BILLING_PLAN_NAME_MIN_LENGTH = 3

	BILLING_PRODUCT_FREE  = "FREE"
	BILLING_PRODUCT_LITE = "LITE"
	BILLING_PRODUCT_PRO   = "PRO"
	BILLING_PRODUCT_ULTRA = "ULTRA"
)
