// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/accounts/service.proto

package accounts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartRegistrationParams struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRegistrationParams) Reset()         { *m = StartRegistrationParams{} }
func (m *StartRegistrationParams) String() string { return proto.CompactTextString(m) }
func (*StartRegistrationParams) ProtoMessage()    {}
func (*StartRegistrationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{0}
}

func (m *StartRegistrationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRegistrationParams.Unmarshal(m, b)
}
func (m *StartRegistrationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRegistrationParams.Marshal(b, m, deterministic)
}
func (m *StartRegistrationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRegistrationParams.Merge(m, src)
}
func (m *StartRegistrationParams) XXX_Size() int {
	return xxx_messageInfo_StartRegistrationParams.Size(m)
}
func (m *StartRegistrationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRegistrationParams.DiscardUnknown(m)
}

var xxx_messageInfo_StartRegistrationParams proto.InternalMessageInfo

func (m *StartRegistrationParams) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *StartRegistrationParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegistrationStarted struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationStarted) Reset()         { *m = RegistrationStarted{} }
func (m *RegistrationStarted) String() string { return proto.CompactTextString(m) }
func (*RegistrationStarted) ProtoMessage()    {}
func (*RegistrationStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{1}
}

func (m *RegistrationStarted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationStarted.Unmarshal(m, b)
}
func (m *RegistrationStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationStarted.Marshal(b, m, deterministic)
}
func (m *RegistrationStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationStarted.Merge(m, src)
}
func (m *RegistrationStarted) XXX_Size() int {
	return xxx_messageInfo_RegistrationStarted.Size(m)
}
func (m *RegistrationStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationStarted.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationStarted proto.InternalMessageInfo

func (m *RegistrationStarted) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type VerifyRegistrationParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRegistrationParams) Reset()         { *m = VerifyRegistrationParams{} }
func (m *VerifyRegistrationParams) String() string { return proto.CompactTextString(m) }
func (*VerifyRegistrationParams) ProtoMessage()    {}
func (*VerifyRegistrationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{2}
}

func (m *VerifyRegistrationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRegistrationParams.Unmarshal(m, b)
}
func (m *VerifyRegistrationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRegistrationParams.Marshal(b, m, deterministic)
}
func (m *VerifyRegistrationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRegistrationParams.Merge(m, src)
}
func (m *VerifyRegistrationParams) XXX_Size() int {
	return xxx_messageInfo_VerifyRegistrationParams.Size(m)
}
func (m *VerifyRegistrationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRegistrationParams.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRegistrationParams proto.InternalMessageInfo

func (m *VerifyRegistrationParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VerifyRegistrationParams) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SendNewRegistrationCodeParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendNewRegistrationCodeParams) Reset()         { *m = SendNewRegistrationCodeParams{} }
func (m *SendNewRegistrationCodeParams) String() string { return proto.CompactTextString(m) }
func (*SendNewRegistrationCodeParams) ProtoMessage()    {}
func (*SendNewRegistrationCodeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{3}
}

func (m *SendNewRegistrationCodeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendNewRegistrationCodeParams.Unmarshal(m, b)
}
func (m *SendNewRegistrationCodeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendNewRegistrationCodeParams.Marshal(b, m, deterministic)
}
func (m *SendNewRegistrationCodeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendNewRegistrationCodeParams.Merge(m, src)
}
func (m *SendNewRegistrationCodeParams) XXX_Size() int {
	return xxx_messageInfo_SendNewRegistrationCodeParams.Size(m)
}
func (m *SendNewRegistrationCodeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SendNewRegistrationCodeParams.DiscardUnknown(m)
}

var xxx_messageInfo_SendNewRegistrationCodeParams proto.InternalMessageInfo

func (m *SendNewRegistrationCodeParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CompleteRegistrationParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AuthKey              []byte   `protobuf:"bytes,3,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteRegistrationParams) Reset()         { *m = CompleteRegistrationParams{} }
func (m *CompleteRegistrationParams) String() string { return proto.CompactTextString(m) }
func (*CompleteRegistrationParams) ProtoMessage()    {}
func (*CompleteRegistrationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{4}
}

func (m *CompleteRegistrationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteRegistrationParams.Unmarshal(m, b)
}
func (m *CompleteRegistrationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteRegistrationParams.Marshal(b, m, deterministic)
}
func (m *CompleteRegistrationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteRegistrationParams.Merge(m, src)
}
func (m *CompleteRegistrationParams) XXX_Size() int {
	return xxx_messageInfo_CompleteRegistrationParams.Size(m)
}
func (m *CompleteRegistrationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteRegistrationParams.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteRegistrationParams proto.InternalMessageInfo

func (m *CompleteRegistrationParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CompleteRegistrationParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CompleteRegistrationParams) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

type SignInParams struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AuthKey              []byte   `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInParams) Reset()         { *m = SignInParams{} }
func (m *SignInParams) String() string { return proto.CompactTextString(m) }
func (*SignInParams) ProtoMessage()    {}
func (*SignInParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{5}
}

func (m *SignInParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInParams.Unmarshal(m, b)
}
func (m *SignInParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInParams.Marshal(b, m, deterministic)
}
func (m *SignInParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInParams.Merge(m, src)
}
func (m *SignInParams) XXX_Size() int {
	return xxx_messageInfo_SignInParams.Size(m)
}
func (m *SignInParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInParams.DiscardUnknown(m)
}

var xxx_messageInfo_SignInParams proto.InternalMessageInfo

func (m *SignInParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInParams) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

type NewSession struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSession) Reset()         { *m = NewSession{} }
func (m *NewSession) String() string { return proto.CompactTextString(m) }
func (*NewSession) ProtoMessage()    {}
func (*NewSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{6}
}

func (m *NewSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSession.Unmarshal(m, b)
}
func (m *NewSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSession.Marshal(b, m, deterministic)
}
func (m *NewSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSession.Merge(m, src)
}
func (m *NewSession) XXX_Size() int {
	return xxx_messageInfo_NewSession.Size(m)
}
func (m *NewSession) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSession.DiscardUnknown(m)
}

var xxx_messageInfo_NewSession proto.InternalMessageInfo

func (m *NewSession) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewSession) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Session struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Device               string   `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Location             string   `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{7}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Session) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Session) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Session) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type Sessions struct {
	Sessions             []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Sessions) Reset()         { *m = Sessions{} }
func (m *Sessions) String() string { return proto.CompactTextString(m) }
func (*Sessions) ProtoMessage()    {}
func (*Sessions) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{8}
}

func (m *Sessions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sessions.Unmarshal(m, b)
}
func (m *Sessions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sessions.Marshal(b, m, deterministic)
}
func (m *Sessions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sessions.Merge(m, src)
}
func (m *Sessions) XXX_Size() int {
	return xxx_messageInfo_Sessions.Size(m)
}
func (m *Sessions) XXX_DiscardUnknown() {
	xxx_messageInfo_Sessions.DiscardUnknown(m)
}

var xxx_messageInfo_Sessions proto.InternalMessageInfo

func (m *Sessions) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type RevokeSessionParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeSessionParams) Reset()         { *m = RevokeSessionParams{} }
func (m *RevokeSessionParams) String() string { return proto.CompactTextString(m) }
func (*RevokeSessionParams) ProtoMessage()    {}
func (*RevokeSessionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{9}
}

func (m *RevokeSessionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeSessionParams.Unmarshal(m, b)
}
func (m *RevokeSessionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeSessionParams.Marshal(b, m, deterministic)
}
func (m *RevokeSessionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeSessionParams.Merge(m, src)
}
func (m *RevokeSessionParams) XXX_Size() int {
	return xxx_messageInfo_RevokeSessionParams.Size(m)
}
func (m *RevokeSessionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeSessionParams.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeSessionParams proto.InternalMessageInfo

func (m *RevokeSessionParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*StartRegistrationParams)(nil), "com.bloom42.StartRegistrationParams")
	proto.RegisterType((*RegistrationStarted)(nil), "com.bloom42.RegistrationStarted")
	proto.RegisterType((*VerifyRegistrationParams)(nil), "com.bloom42.VerifyRegistrationParams")
	proto.RegisterType((*SendNewRegistrationCodeParams)(nil), "com.bloom42.SendNewRegistrationCodeParams")
	proto.RegisterType((*CompleteRegistrationParams)(nil), "com.bloom42.CompleteRegistrationParams")
	proto.RegisterType((*SignInParams)(nil), "com.bloom42.SignInParams")
	proto.RegisterType((*NewSession)(nil), "com.bloom42.NewSession")
	proto.RegisterType((*Session)(nil), "com.bloom42.Session")
	proto.RegisterType((*Sessions)(nil), "com.bloom42.Sessions")
	proto.RegisterType((*RevokeSessionParams)(nil), "com.bloom42.RevokeSessionParams")
}

func init() { proto.RegisterFile("rpc/accounts/service.proto", fileDescriptor_04719010c8d53c2f) }

var fileDescriptor_04719010c8d53c2f = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x8b, 0xd3, 0x4c,
	0x14, 0xc6, 0x69, 0xb7, 0x1f, 0xd9, 0xd3, 0xbe, 0x2f, 0x38, 0xd6, 0x6d, 0x36, 0xb2, 0x50, 0x83,
	0x8b, 0xc5, 0x8b, 0x54, 0xaa, 0x37, 0xc2, 0x2a, 0xac, 0xcb, 0x5e, 0x2c, 0x4a, 0x95, 0x16, 0x44,
	0x14, 0x29, 0xd3, 0xe4, 0x6c, 0x1d, 0x9a, 0x64, 0x42, 0x66, 0xba, 0x4b, 0xc1, 0x3f, 0xdc, 0x4b,
	0xc9, 0x64, 0x5a, 0x92, 0x36, 0xb3, 0x78, 0x97, 0x33, 0xf3, 0xcc, 0xf3, 0xcc, 0xc7, 0xef, 0x04,
	0x9c, 0x34, 0xf1, 0x47, 0xd4, 0xf7, 0xf9, 0x3a, 0x96, 0x62, 0x24, 0x30, 0xbd, 0x63, 0x3e, 0x7a,
	0x49, 0xca, 0x25, 0x27, 0x1d, 0x9f, 0x47, 0xde, 0x22, 0xe4, 0x3c, 0x7a, 0x33, 0x76, 0x9e, 0x2e,
	0x39, 0x5f, 0x86, 0x38, 0x52, 0x53, 0x8b, 0xf5, 0xed, 0x08, 0xa3, 0x44, 0x6e, 0x72, 0xa5, 0x3b,
	0x85, 0xfe, 0x4c, 0xd2, 0x54, 0x4e, 0x71, 0xc9, 0x84, 0x4c, 0xa9, 0x64, 0x3c, 0xfe, 0x42, 0x53,
	0x1a, 0x09, 0xf2, 0x0c, 0xba, 0x01, 0x13, 0x49, 0x48, 0x37, 0xf3, 0x98, 0x46, 0x68, 0xd7, 0x06,
	0xb5, 0xe1, 0xf1, 0xb4, 0xa3, 0xc7, 0x26, 0x34, 0x42, 0xd2, 0x83, 0x26, 0x46, 0x94, 0x85, 0x76,
	0x5d, 0xcd, 0xe5, 0x85, 0x7b, 0x0e, 0x8f, 0x8b, 0x76, 0xca, 0x1f, 0x03, 0xf2, 0x3f, 0xd4, 0x59,
	0xa0, 0x5d, 0xea, 0x2c, 0x70, 0xdf, 0x83, 0xfd, 0x15, 0x53, 0x76, 0xbb, 0xa9, 0xc8, 0xde, 0xd3,
	0x12, 0x02, 0x0d, 0x9f, 0x07, 0xa8, 0x73, 0xd4, 0xb7, 0x3b, 0x82, 0xb3, 0x19, 0xc6, 0xc1, 0x04,
	0xef, 0x8b, 0x06, 0x57, 0x3c, 0xc0, 0x6a, 0x13, 0xd7, 0x07, 0xe7, 0x8a, 0x47, 0x49, 0x88, 0x12,
	0xff, 0x21, 0xd2, 0x01, 0x6b, 0x2d, 0x30, 0x55, 0x47, 0xcf, 0x63, 0x77, 0x35, 0x39, 0x05, 0x8b,
	0xae, 0xe5, 0xaf, 0xf9, 0x0a, 0x37, 0xf6, 0xd1, 0xa0, 0x36, 0xec, 0x4e, 0xdb, 0x59, 0xfd, 0x11,
	0x37, 0xee, 0x35, 0x74, 0x67, 0x6c, 0x19, 0xdf, 0x6c, 0x6d, 0x8b, 0x36, 0xb5, 0x07, 0x6c, 0xea,
	0x65, 0x9b, 0x31, 0xc0, 0x04, 0xef, 0x67, 0x28, 0x04, 0xe3, 0xf1, 0xc1, 0xde, 0x7a, 0xd0, 0x94,
	0x7c, 0x85, 0xf1, 0xf6, 0xde, 0x55, 0xe1, 0xfe, 0x86, 0xb6, 0x69, 0xc1, 0x19, 0x80, 0x9f, 0x22,
	0x95, 0x18, 0xcc, 0xa9, 0xd4, 0xab, 0x8e, 0xf5, 0xc8, 0xa5, 0x54, 0xf2, 0x44, 0x9d, 0x24, 0x93,
	0x27, 0xe4, 0x04, 0x5a, 0x01, 0x66, 0x3c, 0xd9, 0x0d, 0x35, 0xa6, 0xab, 0xec, 0x30, 0x21, 0xf7,
	0xd5, 0xad, 0xd9, 0xcd, 0xfc, 0x30, 0xdb, 0xda, 0xbd, 0x00, 0x4b, 0xa7, 0x0b, 0xf2, 0x0a, 0x2c,
	0xa1, 0xbf, 0xed, 0xda, 0xe0, 0x68, 0xd8, 0x19, 0xf7, 0xbc, 0x02, 0x92, 0x9e, 0x16, 0x4e, 0x77,
	0xaa, 0x9c, 0x99, 0x3b, 0xbe, 0x42, 0x3d, 0x55, 0xfd, 0x28, 0xe3, 0x3f, 0x0d, 0xb0, 0x2e, 0x35,
	0xf3, 0xe4, 0x07, 0x3c, 0x3a, 0x60, 0x97, 0x3c, 0x2f, 0x07, 0x55, 0xb3, 0xed, 0x0c, 0x4a, 0xaa,
	0x2a, 0x5a, 0x67, 0x40, 0x0e, 0xe9, 0x24, 0xe7, 0xa5, 0x75, 0x26, 0x7c, 0x9d, 0x13, 0x2f, 0xef,
	0x39, 0x6f, 0xdb, 0x73, 0xde, 0x75, 0xd6, 0x73, 0xe4, 0x1b, 0xf4, 0xaa, 0x08, 0x24, 0x2f, 0x4a,
	0xb6, 0x66, 0x48, 0x9d, 0x7e, 0x49, 0x58, 0x20, 0xe4, 0x27, 0xf4, 0x0d, 0xcd, 0x40, 0x5e, 0xee,
	0x5d, 0xfd, 0x03, 0x2d, 0x63, 0xdc, 0xf8, 0x05, 0xb4, 0x72, 0xaa, 0xc9, 0x69, 0xd9, 0xad, 0x80,
	0xba, 0x79, 0x73, 0x6f, 0xa1, 0x9d, 0x09, 0x3f, 0xaf, 0x25, 0x31, 0x04, 0x18, 0x83, 0x6f, 0xe0,
	0xbf, 0x12, 0x17, 0x64, 0xff, 0xe5, 0x0e, 0x98, 0x31, 0x5a, 0xbd, 0x83, 0xee, 0x27, 0x26, 0xe4,
	0x0e, 0x52, 0xd3, 0x56, 0x9e, 0x54, 0xa1, 0x2a, 0x3e, 0xc0, 0x77, 0x6b, 0xfb, 0xb7, 0x5d, 0xb4,
	0xd4, 0x92, 0xd7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x1b, 0x10, 0x20, 0x84, 0x05, 0x00,
	0x00,
}
