// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/billing/service.proto

package billing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Plan struct {
	Id                       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Storage                  uint64   `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
	BitflowParallelDownloads uint64   `protobuf:"varint,4,opt,name=bitflow_parallel_downloads,json=bitflowParallelDownloads,proto3" json:"bitflow_parallel_downloads,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{1}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetStorage() uint64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *Plan) GetBitflowParallelDownloads() uint64 {
	if m != nil {
		return m.BitflowParallelDownloads
	}
	return 0
}

type PlanList struct {
	Plans                []*Plan  `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlanList) Reset()         { *m = PlanList{} }
func (m *PlanList) String() string { return proto.CompactTextString(m) }
func (*PlanList) ProtoMessage()    {}
func (*PlanList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{2}
}

func (m *PlanList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanList.Unmarshal(m, b)
}
func (m *PlanList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanList.Marshal(b, m, deterministic)
}
func (m *PlanList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanList.Merge(m, src)
}
func (m *PlanList) XXX_Size() int {
	return xxx_messageInfo_PlanList.Size(m)
}
func (m *PlanList) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanList.DiscardUnknown(m)
}

var xxx_messageInfo_PlanList proto.InternalMessageInfo

func (m *PlanList) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

type DetailedPlan struct {
	Id                       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StripeId                 string   `protobuf:"bytes,3,opt,name=stripe_id,json=stripeId,proto3" json:"stripe_id,omitempty"`
	Storage                  uint64   `protobuf:"varint,4,opt,name=storage,proto3" json:"storage,omitempty"`
	BitflowParallelDownloads uint64   `protobuf:"varint,5,opt,name=bitflow_parallel_downloads,json=bitflowParallelDownloads,proto3" json:"bitflow_parallel_downloads,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *DetailedPlan) Reset()         { *m = DetailedPlan{} }
func (m *DetailedPlan) String() string { return proto.CompactTextString(m) }
func (*DetailedPlan) ProtoMessage()    {}
func (*DetailedPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{3}
}

func (m *DetailedPlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailedPlan.Unmarshal(m, b)
}
func (m *DetailedPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailedPlan.Marshal(b, m, deterministic)
}
func (m *DetailedPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailedPlan.Merge(m, src)
}
func (m *DetailedPlan) XXX_Size() int {
	return xxx_messageInfo_DetailedPlan.Size(m)
}
func (m *DetailedPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailedPlan.DiscardUnknown(m)
}

var xxx_messageInfo_DetailedPlan proto.InternalMessageInfo

func (m *DetailedPlan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DetailedPlan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetailedPlan) GetStripeId() string {
	if m != nil {
		return m.StripeId
	}
	return ""
}

func (m *DetailedPlan) GetStorage() uint64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *DetailedPlan) GetBitflowParallelDownloads() uint64 {
	if m != nil {
		return m.BitflowParallelDownloads
	}
	return 0
}

type DetailedPlanList struct {
	Plans                []*DetailedPlan `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DetailedPlanList) Reset()         { *m = DetailedPlanList{} }
func (m *DetailedPlanList) String() string { return proto.CompactTextString(m) }
func (*DetailedPlanList) ProtoMessage()    {}
func (*DetailedPlanList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{4}
}

func (m *DetailedPlanList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailedPlanList.Unmarshal(m, b)
}
func (m *DetailedPlanList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailedPlanList.Marshal(b, m, deterministic)
}
func (m *DetailedPlanList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailedPlanList.Merge(m, src)
}
func (m *DetailedPlanList) XXX_Size() int {
	return xxx_messageInfo_DetailedPlanList.Size(m)
}
func (m *DetailedPlanList) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailedPlanList.DiscardUnknown(m)
}

var xxx_messageInfo_DetailedPlanList proto.InternalMessageInfo

func (m *DetailedPlanList) GetPlans() []*DetailedPlan {
	if m != nil {
		return m.Plans
	}
	return nil
}

type CreatePlanParams struct {
	Name                     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StripeId                 string   `protobuf:"bytes,2,opt,name=stripe_id,json=stripeId,proto3" json:"stripe_id,omitempty"`
	Storage                  uint64   `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
	BitflowParallelDownloads uint64   `protobuf:"varint,4,opt,name=bitflow_parallel_downloads,json=bitflowParallelDownloads,proto3" json:"bitflow_parallel_downloads,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *CreatePlanParams) Reset()         { *m = CreatePlanParams{} }
func (m *CreatePlanParams) String() string { return proto.CompactTextString(m) }
func (*CreatePlanParams) ProtoMessage()    {}
func (*CreatePlanParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{5}
}

func (m *CreatePlanParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanParams.Unmarshal(m, b)
}
func (m *CreatePlanParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanParams.Marshal(b, m, deterministic)
}
func (m *CreatePlanParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanParams.Merge(m, src)
}
func (m *CreatePlanParams) XXX_Size() int {
	return xxx_messageInfo_CreatePlanParams.Size(m)
}
func (m *CreatePlanParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanParams proto.InternalMessageInfo

func (m *CreatePlanParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePlanParams) GetStripeId() string {
	if m != nil {
		return m.StripeId
	}
	return ""
}

func (m *CreatePlanParams) GetStorage() uint64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *CreatePlanParams) GetBitflowParallelDownloads() uint64 {
	if m != nil {
		return m.BitflowParallelDownloads
	}
	return 0
}

type UpdatePlanParams struct {
	PlanId                   string   `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Name                     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StripeId                 string   `protobuf:"bytes,3,opt,name=stripe_id,json=stripeId,proto3" json:"stripe_id,omitempty"`
	Storage                  uint64   `protobuf:"varint,4,opt,name=storage,proto3" json:"storage,omitempty"`
	BitflowParallelDownloads uint64   `protobuf:"varint,5,opt,name=bitflow_parallel_downloads,json=bitflowParallelDownloads,proto3" json:"bitflow_parallel_downloads,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *UpdatePlanParams) Reset()         { *m = UpdatePlanParams{} }
func (m *UpdatePlanParams) String() string { return proto.CompactTextString(m) }
func (*UpdatePlanParams) ProtoMessage()    {}
func (*UpdatePlanParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{6}
}

func (m *UpdatePlanParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlanParams.Unmarshal(m, b)
}
func (m *UpdatePlanParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlanParams.Marshal(b, m, deterministic)
}
func (m *UpdatePlanParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlanParams.Merge(m, src)
}
func (m *UpdatePlanParams) XXX_Size() int {
	return xxx_messageInfo_UpdatePlanParams.Size(m)
}
func (m *UpdatePlanParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlanParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlanParams proto.InternalMessageInfo

func (m *UpdatePlanParams) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

func (m *UpdatePlanParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePlanParams) GetStripeId() string {
	if m != nil {
		return m.StripeId
	}
	return ""
}

func (m *UpdatePlanParams) GetStorage() uint64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *UpdatePlanParams) GetBitflowParallelDownloads() uint64 {
	if m != nil {
		return m.BitflowParallelDownloads
	}
	return 0
}

type DeletePlanParams struct {
	PlanId               string   `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlanParams) Reset()         { *m = DeletePlanParams{} }
func (m *DeletePlanParams) String() string { return proto.CompactTextString(m) }
func (*DeletePlanParams) ProtoMessage()    {}
func (*DeletePlanParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{7}
}

func (m *DeletePlanParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlanParams.Unmarshal(m, b)
}
func (m *DeletePlanParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlanParams.Marshal(b, m, deterministic)
}
func (m *DeletePlanParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlanParams.Merge(m, src)
}
func (m *DeletePlanParams) XXX_Size() int {
	return xxx_messageInfo_DeletePlanParams.Size(m)
}
func (m *DeletePlanParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlanParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlanParams proto.InternalMessageInfo

func (m *DeletePlanParams) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type ChangePlanParams struct {
	PlanId               string   `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StripePaymentMethod  string   `protobuf:"bytes,2,opt,name=stripe_payment_method,json=stripePaymentMethod,proto3" json:"stripe_payment_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePlanParams) Reset()         { *m = ChangePlanParams{} }
func (m *ChangePlanParams) String() string { return proto.CompactTextString(m) }
func (*ChangePlanParams) ProtoMessage()    {}
func (*ChangePlanParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{8}
}

func (m *ChangePlanParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePlanParams.Unmarshal(m, b)
}
func (m *ChangePlanParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePlanParams.Marshal(b, m, deterministic)
}
func (m *ChangePlanParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePlanParams.Merge(m, src)
}
func (m *ChangePlanParams) XXX_Size() int {
	return xxx_messageInfo_ChangePlanParams.Size(m)
}
func (m *ChangePlanParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePlanParams.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePlanParams proto.InternalMessageInfo

func (m *ChangePlanParams) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

func (m *ChangePlanParams) GetStripePaymentMethod() string {
	if m != nil {
		return m.StripePaymentMethod
	}
	return ""
}

type AddPaymentMethodParams struct {
	StripePaymentMethod  string   `protobuf:"bytes,1,opt,name=stripe_payment_method,json=stripePaymentMethod,proto3" json:"stripe_payment_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPaymentMethodParams) Reset()         { *m = AddPaymentMethodParams{} }
func (m *AddPaymentMethodParams) String() string { return proto.CompactTextString(m) }
func (*AddPaymentMethodParams) ProtoMessage()    {}
func (*AddPaymentMethodParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{9}
}

func (m *AddPaymentMethodParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPaymentMethodParams.Unmarshal(m, b)
}
func (m *AddPaymentMethodParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPaymentMethodParams.Marshal(b, m, deterministic)
}
func (m *AddPaymentMethodParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPaymentMethodParams.Merge(m, src)
}
func (m *AddPaymentMethodParams) XXX_Size() int {
	return xxx_messageInfo_AddPaymentMethodParams.Size(m)
}
func (m *AddPaymentMethodParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPaymentMethodParams.DiscardUnknown(m)
}

var xxx_messageInfo_AddPaymentMethodParams proto.InternalMessageInfo

func (m *AddPaymentMethodParams) GetStripePaymentMethod() string {
	if m != nil {
		return m.StripePaymentMethod
	}
	return ""
}

// TODO
type PaymentMethod struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDefault            bool     `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{10}
}

func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (m *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(m, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethod) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

type PaymentMethodList struct {
	PaymentMethods       []*PaymentMethod `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PaymentMethodList) Reset()         { *m = PaymentMethodList{} }
func (m *PaymentMethodList) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodList) ProtoMessage()    {}
func (*PaymentMethodList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{11}
}

func (m *PaymentMethodList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodList.Unmarshal(m, b)
}
func (m *PaymentMethodList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodList.Marshal(b, m, deterministic)
}
func (m *PaymentMethodList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodList.Merge(m, src)
}
func (m *PaymentMethodList) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodList.Size(m)
}
func (m *PaymentMethodList) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodList.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodList proto.InternalMessageInfo

func (m *PaymentMethodList) GetPaymentMethods() []*PaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

type RemovePaymentMethodParams struct {
	PaymentMethodId      string   `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePaymentMethodParams) Reset()         { *m = RemovePaymentMethodParams{} }
func (m *RemovePaymentMethodParams) String() string { return proto.CompactTextString(m) }
func (*RemovePaymentMethodParams) ProtoMessage()    {}
func (*RemovePaymentMethodParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{12}
}

func (m *RemovePaymentMethodParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePaymentMethodParams.Unmarshal(m, b)
}
func (m *RemovePaymentMethodParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePaymentMethodParams.Marshal(b, m, deterministic)
}
func (m *RemovePaymentMethodParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePaymentMethodParams.Merge(m, src)
}
func (m *RemovePaymentMethodParams) XXX_Size() int {
	return xxx_messageInfo_RemovePaymentMethodParams.Size(m)
}
func (m *RemovePaymentMethodParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePaymentMethodParams.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePaymentMethodParams proto.InternalMessageInfo

func (m *RemovePaymentMethodParams) GetPaymentMethodId() string {
	if m != nil {
		return m.PaymentMethodId
	}
	return ""
}

type UpdateDefaultPaymentMethodParams struct {
	PaymentMethodId      string   `protobuf:"bytes,1,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDefaultPaymentMethodParams) Reset()         { *m = UpdateDefaultPaymentMethodParams{} }
func (m *UpdateDefaultPaymentMethodParams) String() string { return proto.CompactTextString(m) }
func (*UpdateDefaultPaymentMethodParams) ProtoMessage()    {}
func (*UpdateDefaultPaymentMethodParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{13}
}

func (m *UpdateDefaultPaymentMethodParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDefaultPaymentMethodParams.Unmarshal(m, b)
}
func (m *UpdateDefaultPaymentMethodParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDefaultPaymentMethodParams.Marshal(b, m, deterministic)
}
func (m *UpdateDefaultPaymentMethodParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDefaultPaymentMethodParams.Merge(m, src)
}
func (m *UpdateDefaultPaymentMethodParams) XXX_Size() int {
	return xxx_messageInfo_UpdateDefaultPaymentMethodParams.Size(m)
}
func (m *UpdateDefaultPaymentMethodParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDefaultPaymentMethodParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDefaultPaymentMethodParams proto.InternalMessageInfo

func (m *UpdateDefaultPaymentMethodParams) GetPaymentMethodId() string {
	if m != nil {
		return m.PaymentMethodId
	}
	return ""
}

// TODO
type Invoice struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{14}
}

func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (m *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(m, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type InvoiceList struct {
	Invoices             []*Invoice `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InvoiceList) Reset()         { *m = InvoiceList{} }
func (m *InvoiceList) String() string { return proto.CompactTextString(m) }
func (*InvoiceList) ProtoMessage()    {}
func (*InvoiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c569122374058fad, []int{15}
}

func (m *InvoiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceList.Unmarshal(m, b)
}
func (m *InvoiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceList.Marshal(b, m, deterministic)
}
func (m *InvoiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceList.Merge(m, src)
}
func (m *InvoiceList) XXX_Size() int {
	return xxx_messageInfo_InvoiceList.Size(m)
}
func (m *InvoiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceList.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceList proto.InternalMessageInfo

func (m *InvoiceList) GetInvoices() []*Invoice {
	if m != nil {
		return m.Invoices
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "com.bloom42.billing.Empty")
	proto.RegisterType((*Plan)(nil), "com.bloom42.billing.Plan")
	proto.RegisterType((*PlanList)(nil), "com.bloom42.billing.PlanList")
	proto.RegisterType((*DetailedPlan)(nil), "com.bloom42.billing.DetailedPlan")
	proto.RegisterType((*DetailedPlanList)(nil), "com.bloom42.billing.DetailedPlanList")
	proto.RegisterType((*CreatePlanParams)(nil), "com.bloom42.billing.CreatePlanParams")
	proto.RegisterType((*UpdatePlanParams)(nil), "com.bloom42.billing.UpdatePlanParams")
	proto.RegisterType((*DeletePlanParams)(nil), "com.bloom42.billing.DeletePlanParams")
	proto.RegisterType((*ChangePlanParams)(nil), "com.bloom42.billing.ChangePlanParams")
	proto.RegisterType((*AddPaymentMethodParams)(nil), "com.bloom42.billing.AddPaymentMethodParams")
	proto.RegisterType((*PaymentMethod)(nil), "com.bloom42.billing.PaymentMethod")
	proto.RegisterType((*PaymentMethodList)(nil), "com.bloom42.billing.PaymentMethodList")
	proto.RegisterType((*RemovePaymentMethodParams)(nil), "com.bloom42.billing.RemovePaymentMethodParams")
	proto.RegisterType((*UpdateDefaultPaymentMethodParams)(nil), "com.bloom42.billing.UpdateDefaultPaymentMethodParams")
	proto.RegisterType((*Invoice)(nil), "com.bloom42.billing.Invoice")
	proto.RegisterType((*InvoiceList)(nil), "com.bloom42.billing.InvoiceList")
}

func init() { proto.RegisterFile("rpc/billing/service.proto", fileDescriptor_c569122374058fad) }

var fileDescriptor_c569122374058fad = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0x56, 0xba, 0x6e, 0x69, 0xcf, 0xf6, 0xdb, 0x3a, 0x4f, 0x3f, 0x48, 0x03, 0x93, 0x4a, 0xa4,
	0xa1, 0x89, 0x49, 0x9d, 0x54, 0x40, 0x20, 0x81, 0x90, 0xf6, 0x07, 0xa6, 0x6a, 0x63, 0x8c, 0x48,
	0x20, 0xc4, 0x4d, 0x70, 0x6b, 0x6f, 0xb3, 0xe4, 0xc4, 0x51, 0x12, 0x36, 0xed, 0x96, 0xd7, 0xe0,
	0x01, 0x78, 0x01, 0x9e, 0x87, 0x67, 0x41, 0x76, 0xd2, 0x3f, 0x29, 0x71, 0x1a, 0x04, 0x17, 0x5c,
	0x6d, 0x3e, 0xe7, 0xf8, 0xcb, 0xf9, 0xce, 0xe7, 0xcf, 0x2e, 0xb4, 0xa3, 0x70, 0xb8, 0x3b, 0x60,
	0x9c, 0xb3, 0xe0, 0x62, 0x37, 0xa6, 0xd1, 0x15, 0x1b, 0xd2, 0x6e, 0x18, 0x89, 0x44, 0xa0, 0x8d,
	0xa1, 0xf0, 0xbb, 0x03, 0x2e, 0x84, 0xff, 0xa8, 0xd7, 0xcd, 0x4a, 0x1c, 0x13, 0x16, 0x5f, 0xfa,
	0x61, 0x72, 0xe3, 0x7c, 0x31, 0xa0, 0x7e, 0xc6, 0x71, 0x80, 0x56, 0xa1, 0xc6, 0x88, 0x65, 0x74,
	0x8c, 0xed, 0xa6, 0x5b, 0x63, 0x04, 0x21, 0xa8, 0x07, 0xd8, 0xa7, 0x56, 0x4d, 0x45, 0xd4, 0xff,
	0xc8, 0x02, 0x33, 0x4e, 0x44, 0x84, 0x2f, 0xa8, 0xb5, 0xd0, 0x31, 0xb6, 0xeb, 0xee, 0x68, 0x89,
	0x9e, 0x83, 0x3d, 0x60, 0xc9, 0x39, 0x17, 0xd7, 0x5e, 0x88, 0x23, 0xcc, 0x39, 0xe5, 0x1e, 0x11,
	0xd7, 0x01, 0x17, 0x98, 0xc4, 0x56, 0x5d, 0x15, 0x5b, 0x59, 0xc5, 0x59, 0x56, 0x70, 0x38, 0xca,
	0x3b, 0xcf, 0xa0, 0x21, 0x7b, 0x38, 0x61, 0x71, 0x82, 0x76, 0x61, 0x31, 0xe4, 0x38, 0x88, 0x2d,
	0xa3, 0xb3, 0xb0, 0xbd, 0xdc, 0x6b, 0x77, 0x0b, 0xda, 0xef, 0xca, 0x6a, 0x37, 0xad, 0x73, 0xbe,
	0x19, 0xb0, 0x72, 0x48, 0x13, 0xcc, 0x38, 0x25, 0x95, 0x99, 0xdc, 0x81, 0x66, 0x9c, 0x44, 0x2c,
	0xa4, 0x1e, 0x23, 0x8a, 0x4b, 0xd3, 0x6d, 0xa4, 0x81, 0x3e, 0x99, 0xa6, 0x59, 0xff, 0x1d, 0x9a,
	0x8b, 0x73, 0x68, 0x1e, 0x43, 0x6b, 0xba, 0x51, 0x45, 0xf7, 0x49, 0x9e, 0xee, 0xbd, 0x42, 0xba,
	0xd3, 0xbb, 0x46, 0xb4, 0xbf, 0x1a, 0xd0, 0x3a, 0x88, 0x28, 0x4e, 0xa8, 0x8c, 0xca, 0x8f, 0xf9,
	0xf1, 0x98, 0xaa, 0xa1, 0xa3, 0x5a, 0xd3, 0x53, 0xfd, 0xab, 0x8a, 0x7e, 0x37, 0xa0, 0xf5, 0x2e,
	0x24, 0xf9, 0xee, 0x6e, 0x83, 0x29, 0x7b, 0xf7, 0xc6, 0xea, 0x2c, 0xc9, 0x65, 0xff, 0x1f, 0x52,
	0x68, 0x47, 0x2a, 0xc4, 0x69, 0xa5, 0xae, 0x1d, 0x0f, 0x5a, 0x07, 0x97, 0x38, 0xb8, 0xa8, 0x44,
	0xb1, 0x07, 0xff, 0x67, 0x74, 0x42, 0x7c, 0xe3, 0xd3, 0x20, 0xf1, 0x7c, 0x9a, 0x5c, 0x8a, 0x91,
	0x22, 0x1b, 0x69, 0xf2, 0x2c, 0xcd, 0xbd, 0x56, 0x29, 0xe7, 0x04, 0x6e, 0xed, 0x11, 0x92, 0x8b,
	0x65, 0x9f, 0xd1, 0xa2, 0x19, 0x7a, 0xb4, 0x17, 0xf0, 0x5f, 0x2e, 0xf0, 0x8b, 0x4f, 0x36, 0x01,
	0x58, 0xec, 0x11, 0x7a, 0x8e, 0x3f, 0xf3, 0x44, 0xf5, 0xd5, 0x70, 0x9b, 0x2c, 0x3e, 0x4c, 0x03,
	0xce, 0x27, 0x58, 0xcf, 0xed, 0x57, 0xc7, 0xf7, 0x18, 0xd6, 0xf2, 0x1d, 0x8c, 0x0e, 0xb2, 0x53,
	0xec, 0xdb, 0x69, 0x00, 0x77, 0x35, 0x9c, 0x5e, 0xc6, 0xce, 0x11, 0xb4, 0x5d, 0xea, 0x8b, 0x2b,
	0x5a, 0x44, 0xf9, 0x01, 0xac, 0xe7, 0xbf, 0x34, 0x99, 0xf1, 0x5a, 0x0e, 0xa7, 0x4f, 0x9c, 0x53,
	0xe8, 0xa4, 0x87, 0x2f, 0xeb, 0xfd, 0x4f, 0xf1, 0xda, 0x60, 0xf6, 0x83, 0x2b, 0xc1, 0x86, 0x74,
	0x76, 0x68, 0xce, 0x11, 0x2c, 0x67, 0x29, 0x35, 0x8f, 0xa7, 0xd0, 0x60, 0xe9, 0x72, 0x34, 0x88,
	0xbb, 0x85, 0x83, 0xc8, 0xf6, 0xb8, 0xe3, 0xea, 0xde, 0x0f, 0x13, 0xcc, 0xfd, 0x34, 0x8b, 0xde,
	0x03, 0x4c, 0xac, 0x8d, 0xb6, 0x0a, 0x11, 0x66, 0xbd, 0x6f, 0xcf, 0xbf, 0x3a, 0x24, 0xee, 0xc4,
	0x94, 0x1a, 0xdc, 0x59, 0xd7, 0x56, 0xc1, 0x7d, 0x03, 0x30, 0xb1, 0x8d, 0x06, 0x77, 0xd6, 0x57,
	0xb6, 0x5d, 0x58, 0xa6, 0x5e, 0x25, 0xf4, 0x16, 0x56, 0xe4, 0x38, 0xf7, 0x38, 0x97, 0x1b, 0x62,
	0x54, 0x52, 0x6b, 0x6f, 0xcd, 0xed, 0x4f, 0x29, 0xf3, 0x0a, 0x9a, 0xf2, 0xef, 0x7c, 0xbc, 0x4d,
	0xed, 0x8b, 0xa3, 0x70, 0x4e, 0x01, 0x26, 0xae, 0xd7, 0x69, 0x33, 0x73, 0x2d, 0xd8, 0xfa, 0x57,
	0x0c, 0x0d, 0xa1, 0x35, 0x6b, 0x72, 0xb4, 0x53, 0x58, 0x5e, 0x7c, 0x17, 0xd8, 0x15, 0x9c, 0x86,
	0x30, 0x6c, 0x14, 0x38, 0x0b, 0x75, 0x0b, 0xb7, 0x6a, 0x3d, 0x58, 0x2a, 0xd9, 0x35, 0xd8, 0x7a,
	0xcf, 0xa1, 0xc7, 0x25, 0x67, 0x4d, 0x6f, 0xd2, 0x4a, 0xdc, 0x3e, 0x00, 0x52, 0xc2, 0xe6, 0xee,
	0x92, 0x52, 0x85, 0xef, 0xcf, 0x47, 0x55, 0x52, 0x9f, 0xa4, 0xa7, 0x30, 0xf3, 0x6a, 0x39, 0x66,
	0xa7, 0xcc, 0xe6, 0x12, 0x65, 0xbf, 0xf9, 0xd1, 0xcc, 0xc2, 0x83, 0x25, 0xf5, 0xcb, 0xec, 0xe1,
	0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x56, 0x8c, 0xd5, 0xb6, 0x09, 0x00, 0x00,
}
