#!/bin/bash -e

# PostgreSQL settings
DATABASE_URL=$DATABASE_URL

# OpenSSL settings
ENCRYPTION_KEY=$ENCRYPTION_KEY
ENCRYPTION_CIPHER=$ENCRYPTION_CIPHER

# Amazon settings
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
AWS_S3_BUCKET=$S3_BUCKET_NAME


DATE=$(date +%Y-%m-%d_%H-%M-%S)
echo $DATE
