// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/accounts/service.proto

package accounts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInParams struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AuthKey              []byte   `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInParams) Reset()         { *m = SignInParams{} }
func (m *SignInParams) String() string { return proto.CompactTextString(m) }
func (*SignInParams) ProtoMessage()    {}
func (*SignInParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{0}
}

func (m *SignInParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInParams.Unmarshal(m, b)
}
func (m *SignInParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInParams.Marshal(b, m, deterministic)
}
func (m *SignInParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInParams.Merge(m, src)
}
func (m *SignInParams) XXX_Size() int {
	return xxx_messageInfo_SignInParams.Size(m)
}
func (m *SignInParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInParams.DiscardUnknown(m)
}

var xxx_messageInfo_SignInParams proto.InternalMessageInfo

func (m *SignInParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInParams) GetAuthKey() []byte {
	if m != nil {
		return m.AuthKey
	}
	return nil
}

type Session struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_04719010c8d53c2f, []int{1}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*SignInParams)(nil), "com.bloom42.SignInParams")
	proto.RegisterType((*Session)(nil), "com.bloom42.Session")
}

func init() { proto.RegisterFile("rpc/accounts/service.proto", fileDescriptor_04719010c8d53c2f) }

var fileDescriptor_04719010c8d53c2f = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xbd, 0x4e, 0xc3, 0x40,
	0x10, 0x84, 0x65, 0x4b, 0xc4, 0xce, 0x12, 0x28, 0x4e, 0x11, 0x4a, 0x4c, 0x13, 0xa5, 0x4a, 0x75,
	0x96, 0x02, 0x4d, 0x2a, 0x04, 0x52, 0x0a, 0x44, 0x01, 0x72, 0x3a, 0x1a, 0x64, 0x3b, 0x8b, 0x39,
	0x39, 0x77, 0x6b, 0xdd, 0x4f, 0x24, 0x3f, 0x1e, 0x6f, 0x86, 0xfc, 0x87, 0x42, 0x41, 0x91, 0x72,
	0x6e, 0x76, 0xe7, 0xbe, 0x59, 0x88, 0x74, 0x95, 0xc7, 0x69, 0x9e, 0x93, 0x53, 0xd6, 0xc4, 0x06,
	0xf5, 0x51, 0xe4, 0xc8, 0x2b, 0x4d, 0x96, 0xd8, 0x65, 0x4e, 0x92, 0x67, 0x07, 0x22, 0x79, 0xbf,
	0x8e, 0x6e, 0x0b, 0xa2, 0xe2, 0x80, 0x71, 0x6b, 0x65, 0xee, 0x33, 0x46, 0x59, 0xd9, 0xba, 0x9b,
	0x5c, 0x6e, 0x61, 0xb2, 0x13, 0x85, 0x7a, 0x56, 0x6f, 0xa9, 0x4e, 0xa5, 0x61, 0x11, 0x84, 0xce,
	0xa0, 0x56, 0xa9, 0xc4, 0x99, 0xb7, 0xf0, 0x56, 0xe3, 0xe4, 0x57, 0xb3, 0x39, 0x84, 0xa9, 0xb3,
	0x5f, 0x1f, 0x25, 0xd6, 0x33, 0x7f, 0xe1, 0xad, 0x26, 0x49, 0xd0, 0xe8, 0x17, 0xac, 0x97, 0x31,
	0x04, 0x3b, 0x34, 0x46, 0x90, 0x62, 0xd7, 0xe0, 0x8b, 0x7d, 0xbf, 0xeb, 0x8b, 0x3d, 0x9b, 0xc2,
	0x85, 0xa5, 0x12, 0x55, 0xbb, 0x32, 0x4e, 0x3a, 0xb1, 0xfe, 0xf6, 0x20, 0x7c, 0xec, 0xe1, 0xd9,
	0x06, 0x46, 0x1d, 0x04, 0x9b, 0xf3, 0x13, 0x72, 0x7e, 0x4a, 0x16, 0x4d, 0xff, 0x5a, 0xfd, 0x6f,
	0x1b, 0x08, 0x9a, 0xa9, 0x57, 0x67, 0xd9, 0x0d, 0xef, 0x8a, 0xf2, 0xa1, 0x28, 0xdf, 0x36, 0x45,
	0xa3, 0x7f, 0xde, 0xd9, 0x03, 0x5c, 0x25, 0x78, 0xa4, 0x12, 0x87, 0xac, 0x33, 0x03, 0x9e, 0xe0,
	0x3d, 0x1c, 0xee, 0x9f, 0x8d, 0x5a, 0xef, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x88, 0x90,
	0x84, 0x96, 0x01, 0x00, 0x00,
}
