// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package messages

// This schema is only used to auto genrate the struct for the communication between the core and
// the apps.
type CreateNoteParams struct {
	Title string `json:"title"`
	Body  string `json:"body"`
	Color string `json:"color"`
}
